image: alpine/edge
secrets:
  - 88cce185-d2ec-4573-9546-e33f36f79bbf
sources:
  - git+ssh://git@git.sr.ht/~swaits/aoc2023
tasks:
  - mirror-to-github: |
      cd ~/aoc2023
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git remote add github git@github.com:swaits/aoc2023.git
      git push --mirror github
